### ISSUE TITLE
Sprint 2 GIF walkthrough

### ISSUE THREAD

**Issue by ns0714** [AndroidTresLeches/AADP_AndroidClient#40]
/cc @codepathreview @thecodepath 

Please take a look at our GIF walkthrough
https://github.com/AndroidTresLeches/AADP_AndroidClient/blob/master/README.md

**Comment by codepathreview** [comment]
:+1: Good work overall team !!!
- Try to challenge yourself on the UI/visual side of things in the coming days. Not necessarily flashy things, but it's the small details that take a lot of work.
- Good work implementing the core flows. You guys have made great progress in sprint 2 and it seems like most of your application logic is in place.
- It will be good to see if each team member [contributes](https://github.com/AndroidTresLeches/AADP_AndroidClient/graphs/contributors) equally to the group project. This will help everyone learn equally also. 
- Please keep your milestones/issues up to date so that you can track your progress better. I see that you closed almost all sprint 2 tasks and have tasks created for sprint 3 as well, good job.

Take time next week to clean up and polish your app. Generally, most of these tasks are small and easy, but go a long way in making an impact on how your app will get perceived. Also, don't forget to start thinking about your project presentation for the internal demo day. Excited to see your progress next week!

**Comment by paragsagar** [comment]
closing
