### ISSUE TITLE
Sprint #1 tasks

### ISSUE THREAD

**Issue by ns0714** [AndroidTresLeches/AADP_AndroidClient#7]
Can you please review the issues we have created for Sprint 1.

@nesquena @thecodepath

**Comment by paragsagar** [comment]
@nesquena @thecodepath @codepathreview 

The tasks are open and not assigned to anyone in the team.
We will assign them once we start working on it

**Comment by codepathreview** [comment]
:+1: Nice work creating tasks for sprint 1. The goal of this sprint is to have the basic screens and workflows ready as much as possible. A few notes
- Tasks are well defined and seem achievable in the given timeframe
- Pls assign tasks to team members keeping in mind that work load needs to be divided equally among all members of the team. This is critical in working as a team and also gives equal learning opportunity to everyone involved.
- Consider diving a bigger parent task into a number of smaller subtasks - provides a better picture of the progress on the issue(eg. break down StoryList and EventList Fragment tasks into smaller tasks)
- Nice work creating and distributing tasks to create database schema and models.
- Consider creating a project wiki so you can have a thorough documentation of all design decisions made during the project. You have a good start on this by listing down required and advanced features on ReadMe.
- Depending on the strategy your group has come up with, consider creating regular check ins to sync up your code to avoid having multiple errors at the end.
- Consider creating tasks to QA the app a few times to check the basic flow. Integration testing will especially be important for this project since each team member is working on a separate module. The best part is seeing it all come together into a polished app.

Consider incorporating as many screens as possible in this sprint so you can have enough time to add UI polish and advanced features later on. It is those little extra things you do that make everything feel more polished and desirable to use. Look forward to what you all come up with.

**Comment by paragsagar** [comment]
Closing as end of sprint 1
